name: autobrep
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pythonocc-core=7.5.1
  - pip=25.0
  - pip:
    - typing_extensions
    - git+https://github.com/AutodeskAILab/occwl.git@418deb247e6d0bb2beb59dd3c610edeb94f4ee77
    - -e ./core[data,dev]
